'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./_components/NavBar/NavBar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import "@fortawesome/fontawesome-free/css/all.min.css";
import { Provider } from "react-redux";
import { store } from "@/lib/Redux/Store";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <title>Linked Posts</title>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
        <Provider store={store}>
          <NavBar/>
        <div className="container mx-auto mt-10 ">
        <AppRouterCacheProvider>
        {children}
        </AppRouterCacheProvider>
        </div>
        </Provider>
      </body>
    </html>
  );
}
